"""
ifb_export.py  —  Génération de scripts SLURM et notebooks Jupyter pour l'IFB
──────────────────────────────────────────────────────────────────────────────
Pas de dépendance Streamlit : utilisable en dehors de l'app.

Fonctions publiques :
    make_sbatch(tool, db, db_rel, user_params) -> str
    make_notebook(tool, db, db_rel, user_params) -> dict  (structure nbformat)
    notebook_to_json(nb) -> str
"""

import json
import textwrap
from datetime import datetime

# ─────────────────────────────────────────────────────────────────────────────
# TEMPLATES SLURM PAR OUTIL
# Chaque template reçoit un dict de variables via .format(**ctx)
# ─────────────────────────────────────────────────────────────────────────────

_SLURM_HEADER = """\
#!/bin/bash
#SBATCH --job-name={job_name}
#SBATCH --output=logs/{job_name}_%j.out
#SBATCH --error=logs/{job_name}_%j.err
#SBATCH --cpus-per-task={cpus}
#SBATCH --mem={mem}G
#SBATCH --time={time}
#SBATCH --partition=fast
# Generated by TaxProfiling Catalogue — {date}
# Tool    : {tool_name} {tool_version}
# Database: {db_name} {db_release}

set -euo pipefail
mkdir -p logs results

INPUT_FASTQ_R1="{input_fastq_r1}"   # ← replace with your own fastq
INPUT_FASTQ_R2="{input_fastq_r2}"   # ← replace with your own fastq
OUTPUT_DIR="results/{job_name}"
mkdir -p "$OUTPUT_DIR"

"""

# ── Sylph ────────────────────────────────────────────────────────────────────
_SBATCH_SYLPH = _SLURM_HEADER + """\
# ── Sylph sketch ──────────────────────────────────────────────────────────────
DB_PATH="{db_path}"   # ← chemin vers la base sylph (.syldb)

sylph sketch -1 "$INPUT_FASTQ_R1" -2 "$INPUT_FASTQ_R2" -d "$OUTPUT_DIR" -t {cpus}

# ── Sylph profile ─────────────────────────────────────────────────────────────
sylph profile "$DB_PATH" *.fastq.gz.paired.sylsp  \\
    -t {cpus} \\
    -o "$OUTPUT_DIR/profile.tsv"

sylph-tax taxprof "$OUTPUT_DIR/profile.tsv" \\
    -o "$OUTPUT_DIR" \\
    -t GlobDB_r226 "$DB_PATH" \\
    
echo "Done — results in $OUTPUT_DIR/profile.tsv"
"""

# ── SingleM ──────────────────────────────────────────────────────────────────
_SBATCH_SINGLEM = _SLURM_HEADER + """\
# ── SingleM pipe ──────────────────────────────────────────────────────────────
METAPACKAGE="{db_path}"   # ← chemin vers le metapackage SingleM (.smpkg)

singlem pipe \\
    --forward "$INPUT_FASTQ_R1" \\
    --reverse "$INPUT_FASTQ_R2" \\
    --singlem-packages "$METAPACKAGE" \\
    --taxonomic-profile "$OUTPUT_DIR/profile.tsv" \\
    --threads {cpus}

# ── SingleM summarise ─────────────────────────────────────────────────────────
singlem summarise \\
    --input-taxonomic-profile "$OUTPUT_DIR/profile.tsv" \\
    --output-species-by-site-relative-abundance "$OUTPUT_DIR/profile_species.tsv " \\
    --output-species-by-site-level species
    

echo "Done — profil dans $OUTPUT_DIR/profile.tsv"
"""

# ── Meteor ───────────────────────────────────────────────────────────────────
_SBATCH_METEOR = _SLURM_HEADER + """\
# ── Téléchargement de la référence (si pas déjà fait) ─────────────────────────
REF_DIR="{db_path}"   # ← dossier de référence meteor (meteor download ...)
# meteor download -i -c {db_id} -o "$REF_DIR"

# ── Meteor mapping ────────────────────────────────────────────────────────────
meteor mapping \\
    --in-fastq "$INPUT_FASTQ" \\
    --ref-dir "$REF_DIR" \\
    --out-dir "$OUTPUT_DIR" \\
    --threads {cpus}

# ── Meteor profiling ──────────────────────────────────────────────────────────
meteor profiling \\
    --in-dir "$OUTPUT_DIR" \\
    --ref-dir "$REF_DIR" \\
    --out-dir "$OUTPUT_DIR/profile"

echo "Done — profil dans $OUTPUT_DIR/profile/"
"""

# ── Kraken2 + Bracken ────────────────────────────────────────────────────────
_SBATCH_KRAKEN2 = _SLURM_HEADER + """\
# ── Kraken2 ───────────────────────────────────────────────────────────────────
DB_PATH="{db_path}"   # ← dossier de la base Kraken2

kraken2 \\
    --db "$DB_PATH" \\
    --threads {cpus} \\
    --output "$OUTPUT_DIR/kraken2.out" \\
    --report "$OUTPUT_DIR/kraken2_report.txt" \\
    "$INPUT_FASTQ"

# ── Bracken (re-estimation d'abondance) ───────────────────────────────────────
bracken \\
    -d "$DB_PATH" \\
    -i "$OUTPUT_DIR/kraken2_report.txt" \\
    -o "$OUTPUT_DIR/bracken_species.txt" \\
    -l S \\
    -t 10

echo "Done — profil Bracken dans $OUTPUT_DIR/bracken_species.txt"
"""

# ── MetaPhlAn ────────────────────────────────────────────────────────────────
_SBATCH_METAPHLAN = _SLURM_HEADER + """\
# ── MetaPhlAn ─────────────────────────────────────────────────────────────────
DB_PATH="{db_path}"   # ← dossier contenant la base ChocoPhlan

metaphlan "$INPUT_FASTQ" \\
    --input_type fastq \\
    --bowtie2db "$DB_PATH" \\
    --nproc {cpus} \\
    -o "$OUTPUT_DIR/metaphlan_profile.txt" \\
    --bowtie2out "$OUTPUT_DIR/metaphlan.bowtie2.bz2"

echo "Done — profil dans $OUTPUT_DIR/metaphlan_profile.txt"
"""

# ── Metabuli ─────────────────────────────────────────────────────────────────
_SBATCH_METABULI = _SLURM_HEADER + """\
# ── Metabuli classify ─────────────────────────────────────────────────────────
DB_PATH="{db_path}"   # ← dossier de la base Metabuli (GTDB ou RefSeq)

metabuli classify \\
    "$INPUT_FASTQ" \\
    "$DB_PATH" \\
    "$OUTPUT_DIR" \\
    --threads {cpus}

echo "Done — résultats dans $OUTPUT_DIR/"
"""

# ── Générique (outil non reconnu) ────────────────────────────────────────────
_SBATCH_GENERIC = _SLURM_HEADER + """\
# ── Commande générique ────────────────────────────────────────────────────────
# Remplacez par la commande réelle de {tool_name}
DB_PATH="{db_path}"

echo "Outil : {tool_name}"
echo "Base  : {db_name}"
echo "Input : $INPUT_FASTQ"
echo "→ Ajoutez la commande d'exécution ici"
"""

_SBATCH_TEMPLATES: dict[str, str] = {
    "sylph": _SBATCH_SYLPH,
    "singlem": _SBATCH_SINGLEM,
    "meteor": _SBATCH_METEOR,
    "kraken": _SBATCH_KRAKEN2,
    "kraken2": _SBATCH_KRAKEN2,
    "bracken": _SBATCH_KRAKEN2,
    "metaphlan": _SBATCH_METAPHLAN,
    "metabuli": _SBATCH_METABULI,
}

# ─────────────────────────────────────────────────────────────────────────────
# PARAMÈTRES SLURM PAR DÉFAUT PAR OUTIL
# ─────────────────────────────────────────────────────────────────────────────
_SLURM_DEFAULTS: dict[str, dict] = {
    "sylph": {"cpus": 8, "mem": 32, "time": "02:00:00"},
    "singlem": {"cpus": 8, "mem": 8, "time": "04:00:00"},
    "meteor": {"cpus": 16, "mem": 64, "time": "08:00:00"},
    "kraken": {"cpus": 16, "mem": 128, "time": "04:00:00"},
    "kraken2": {"cpus": 16, "mem": 128, "time": "04:00:00"},
    "bracken": {"cpus": 4, "mem": 32, "time": "01:00:00"},
    "metaphlan": {"cpus": 8, "mem": 32, "time": "04:00:00"},
    "metabuli": {"cpus": 16, "mem": 64, "time": "06:00:00"},
    "_default": {"cpus": 8, "mem": 32, "time": "04:00:00"},
}


def _get_db_path(db: dict, db_id: str, tool_id: str, db_rel: dict) -> str:
    """
    Cherche le meilleur chemin IFB disponible pour cette BD + outil.
    Retourne un placeholder si rien de trouvé.
    """
    for ct in db.get("compatible_tools", []) if db else []:
        if not isinstance(ct, dict) or ct.get("@id") != tool_id:
            continue
        for variant in ct.get("DB", []):
            if not isinstance(variant, dict):
                continue
            ifb = variant.get("ifb_server")
            if isinstance(ifb, dict) and ifb.get("path"):
                return ifb["path"]
    return f"/path/to/{db_id}"


def _normalize_tool_id(tool_id: str) -> str:
    return tool_id.lower().replace("-", "").replace("_", "")


def make_sbatch(
    tool: dict,
    db: dict,
    db_id: str,
    db_rel: dict,
    user_params: dict | None = None,
) -> str:
    """
    Génère un script SLURM sbatch pour le couple outil/BD.

    user_params (optionnel) :
        cpus, mem, time, input_fastq
    """
    user_params = user_params or {}
    tool_id = tool.get("@id", "unknown")
    tool_key = _normalize_tool_id(tool_id)

    defaults = _SLURM_DEFAULTS.get(tool_key, _SLURM_DEFAULTS["_default"])
    template = _SBATCH_TEMPLATES.get(tool_key, _SBATCH_GENERIC)

    db_name = db.get("name", db_id) if db else db_id
    db_release = db_rel.get("release") or (db_release_from_db(db) if db else "—")
    db_path = _get_db_path(db, db_id, tool_id, db_rel)

    ctx = {
        "job_name": f"{tool_key}_{db_id}",
        "tool_name": tool.get("name", tool_id),
        "tool_version": tool.get("latest_release") or "latest",
        "db_name": db_name,
        "db_id": db_id,
        "db_release": str(db_release) if db_release else "—",
        "db_path": user_params.get("db_path") or db_path,
        "cpus": user_params.get("cpus", defaults["cpus"]),
        "mem": user_params.get("mem", defaults["mem"]),
        "time": user_params.get("time", defaults["time"]),
        "input_fastq": user_params.get("input_fastq", "/path/to/sample.fastq.gz"),
        "date": datetime.now().strftime("%Y-%m-%d"),
    }
    return template.format(**ctx)


def db_release_from_db(db: dict) -> str:
    return db.get("latest_release") or db.get("release") or "—"


# ─────────────────────────────────────────────────────────────────────────────
# GÉNÉRATION NOTEBOOK JUPYTER (nbformat v4)
# ─────────────────────────────────────────────────────────────────────────────


def _md_cell(source: str) -> dict:
    return {
        "cell_type": "markdown",
        "metadata": {},
        "source": textwrap.dedent(source).strip(),
    }


def _code_cell(source: str, tags: list[str] | None = None) -> dict:
    meta = {}
    if tags:
        meta["tags"] = tags
    return {
        "cell_type": "code",
        "execution_count": None,
        "metadata": meta,
        "outputs": [],
        "source": textwrap.dedent(source).strip(),
    }


def make_notebook(
    tool: dict,
    db: dict,
    db_id: str,
    db_rel: dict,
    user_params: dict | None = None,
) -> dict:
    """
    Génère un notebook Jupyter (nbformat v4) pour le couple outil/BD.
    Retourne un dict sérialisable en JSON.
    """
    user_params = user_params or {}
    tool_id = tool.get("@id", "unknown")
    tool_name = tool.get("name", tool_id)
    tool_ver = tool.get("latest_release") or "latest"
    db_name = db.get("name", db_id) if db else db_id
    db_release = db_rel.get("release") or (db_release_from_db(db) if db else "—")
    db_path = user_params.get("db_path") or _get_db_path(db, db_id, tool_id, db_rel)
    input_fq = user_params.get("input_fastq", "/path/to/sample.fastq.gz")
    tool_key = _normalize_tool_id(tool_id)
    defaults = _SLURM_DEFAULTS.get(tool_key, _SLURM_DEFAULTS["_default"])
    taxa = (
        ", ".join(
            t.get("label", "")
            for t in (db or {}).get("taxonomic_scope", [])
            if isinstance(t, dict) and t.get("label")
        )
        or "—"
    )
    ts_display = _taxo_badge(db_rel.get("taxonomy_system"))
    doc_url = tool.get("doc") or tool.get("repo") or ""

    cells = []

    # ── Titre ─────────────────────────────────────────────────────────────────
    cells.append(_md_cell(f"""\
        # 🧬 Profiling Taxonomique — {tool_name} + {db_name}

        **Outil** : [{tool_name} {tool_ver}]({doc_url})  
        **Base de données** : {db_name} (release {db_release})  
        **Taxonomie** : {ts_display}  
        **Taxons couverts** : {taxa}  

        *Généré par TaxProfiling Catalogue — {datetime.now().strftime("%Y-%m-%d")}*
        """))

    # ── Prérequis ─────────────────────────────────────────────────────────────
    cells.append(_md_cell("""\
        ## 0 · Prérequis

        Ce notebook est conçu pour être exécuté sur le **cluster IFB core-cluster**
        via JupyterHub (OpenOnDemand).  
        Assurez-vous que l'outil est disponible dans votre environnement conda.
        """))

    cells.append(
        _code_cell(
            f"""\
        # Vérifier que l'outil est disponible
        import subprocess, shutil, sys

        tool_bin = shutil.which("{tool_key}")
        if tool_bin:
            print(f"✅ {tool_name} trouvé : {{tool_bin}}")
            result = subprocess.run(["{tool_key}", "--version"],
                                    capture_output=True, text=True)
            print(result.stdout or result.stderr)
        else:
            print("❌ {tool_name} non trouvé dans le PATH.")
            print("   Activez votre environnement conda : conda activate <env>")
        """,
            tags=["setup"],
        )
    )

    # ── Paramètres ────────────────────────────────────────────────────────────
    cells.append(_md_cell("""\
        ## 1 · Paramètres

        Modifiez les chemins ci-dessous avant d'exécuter le notebook.
        """))

    cells.append(
        _code_cell(
            f"""\
        from pathlib import Path

        # ── À modifier ────────────────────────────────────────────────────────
        INPUT_FASTQ = Path("{input_fq}")
        DB_PATH     = Path("{db_path}")
        OUTPUT_DIR  = Path("results/{tool_key}_{db_id}")
        N_THREADS   = {defaults["cpus"]}

        # ── Création des dossiers ─────────────────────────────────────────────
        OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

        print(f"Input  : {{INPUT_FASTQ}}")
        print(f"DB     : {{DB_PATH}}")
        print(f"Output : {{OUTPUT_DIR}}")
        assert INPUT_FASTQ.exists(), f"FASTQ introuvable : {{INPUT_FASTQ}}"
        assert DB_PATH.exists(),     f"Base de données introuvable : {{DB_PATH}}"
        print("✅ Chemins OK")
        """,
            tags=["parameters"],
        )
    )

    # ── Exécution ─────────────────────────────────────────────────────────────
    cells.append(_md_cell("## 2 · Exécution"))
    cells += _execution_cells(tool_key, tool_name, db_id)

    # ── Résultats ─────────────────────────────────────────────────────────────
    cells.append(_md_cell("""\
        ## 3 · Exploration des résultats

        Le fichier de sortie est un tableau TSV avec les colonnes :
        - `clade_name` : nom taxonomique (format GTDB ou NCBI selon la BD)
        - `relative_abundance` : abondance relative (%)

        *Format exact selon l'outil — consultez la documentation.*
        """))

    cells.append(_code_cell("""\
        import pandas as pd

        # Adapter le nom du fichier selon l'outil
        result_files = list(OUTPUT_DIR.glob("*.tsv")) + list(OUTPUT_DIR.glob("*.txt"))
        if not result_files:
            print("Aucun fichier de résultat trouvé. Vérifiez que l'étape 2 s'est bien exécutée.")
        else:
            result_file = result_files[0]
            print(f"Fichier de résultats : {result_file}")
            df = pd.read_csv(result_file, sep="\\t", comment="#")
            print(f"\\n{len(df)} lignes, colonnes : {list(df.columns)}")
            df.head(20)
        """))

    # ── Visualisation ─────────────────────────────────────────────────────────
    cells.append(_md_cell("## 4 · Visualisation"))

    cells.append(_code_cell("""\
        import matplotlib.pyplot as plt
        import matplotlib.ticker as mticker

        # Adapter selon les colonnes réelles de votre fichier
        abund_col = next(
            (c for c in df.columns if "abund" in c.lower() or "fraction" in c.lower()),
            df.columns[-1]
        )
        name_col = df.columns[0]

        # Top 15 taxons
        top = (
            df[df[abund_col] > 0]
            .nlargest(15, abund_col)
            .sort_values(abund_col)
        )

        fig, ax = plt.subplots(figsize=(9, 6))
        bars = ax.barh(top[name_col].str.split("|").str[-1], top[abund_col],
                       color="#534AB7", edgecolor="white", linewidth=0.5)
        ax.set_xlabel("Abondance relative (%)", fontsize=11)
        ax.set_title(f"Top 15 taxons — {tool_name} + {db_name}", fontsize=13, pad=12)
        ax.xaxis.set_major_formatter(mticker.PercentFormatter(xmax=1.0
            if top[abund_col].max() <= 1 else 100))
        ax.spines[["top","right"]].set_visible(False)
        plt.tight_layout()
        plt.savefig(OUTPUT_DIR / "top15_abundance.png", dpi=150, bbox_inches="tight")
        plt.show()
        print("Figure sauvegardée dans", OUTPUT_DIR / "top15_abundance.png")
        """.replace("{tool_name}", tool_name).replace("{db_name}", db_name)))

    # ── Metadata ──────────────────────────────────────────────────────────────
    nb = {
        "nbformat": 4,
        "nbformat_minor": 5,
        "metadata": {
            "kernelspec": {
                "display_name": "Python 3",
                "language": "python",
                "name": "python3",
            },
            "language_info": {"name": "python", "version": "3.10.0"},
        },
        "cells": cells,
    }
    return nb


def notebook_to_json(nb: dict) -> str:
    return json.dumps(nb, ensure_ascii=False, indent=1)


# ─────────────────────────────────────────────────────────────────────────────
# CELLULES D'EXÉCUTION SPÉCIFIQUES PAR OUTIL
# ─────────────────────────────────────────────────────────────────────────────
def _execution_cells(tool_key: str, tool_name: str, db_id: str) -> list[dict]:
    if tool_key == "sylph":
        return [
            _code_cell("""\
                import subprocess

                # Sketch des reads
                sketch_out = OUTPUT_DIR / "reads.sylsp"
                cmd_sketch = [
                    "sylph", "sketch", str(INPUT_FASTQ),
                    "-o", str(sketch_out),
                    "-t", str(N_THREADS),
                ]
                print("Sketch:", " ".join(cmd_sketch))
                subprocess.run(cmd_sketch, check=True)
                print("✅ Sketch terminé")
                """),
            _code_cell("""\
                # Profile
                profile_out = OUTPUT_DIR / "profile.tsv"
                cmd_profile = [
                    "sylph", "profile", str(DB_PATH), str(sketch_out),
                    "-t", str(N_THREADS),
                    "-o", str(profile_out),
                ]
                print("Profile:", " ".join(cmd_profile))
                subprocess.run(cmd_profile, check=True)
                print("✅ Profiling terminé →", profile_out)
                """),
        ]

    if tool_key == "singlem":
        return [_code_cell("""\
            import subprocess

            otu_out     = OUTPUT_DIR / "otu_table.tsv"
            profile_out = OUTPUT_DIR / "profile.tsv"

            cmd = [
                "singlem", "pipe",
                "--forward", str(INPUT_FASTQ),
                "--metapackage", str(DB_PATH),
                "--otu-table", str(otu_out),
                "--threads", str(N_THREADS),
            ]
            print("Commande:", " ".join(cmd))
            subprocess.run(cmd, check=True)

            subprocess.run([
                "singlem", "summarise",
                "--input-otu-tables", str(otu_out),
                "--taxonomic-profile", str(profile_out),
            ], check=True)
            print("✅ Profiling terminé →", profile_out)
            """)]

    if tool_key == "meteor":
        return [
            _code_cell(f"""\
                import subprocess

                # Téléchargement de la référence (si nécessaire)
                # subprocess.run(["meteor", "download", "-i", "-c", "{db_id}",
                #                 "-o", str(DB_PATH)], check=True)

                # Mapping
                cmd_map = [
                    "meteor", "mapping",
                    "--in-fastq", str(INPUT_FASTQ),
                    "--ref-dir", str(DB_PATH),
                    "--out-dir", str(OUTPUT_DIR),
                    "--threads", str(N_THREADS),
                ]
                print("Mapping:", " ".join(cmd_map))
                subprocess.run(cmd_map, check=True)
                print("✅ Mapping terminé")
                """),
            _code_cell("""\
                # Profiling
                cmd_prof = [
                    "meteor", "profiling",
                    "--in-dir",  str(OUTPUT_DIR),
                    "--ref-dir", str(DB_PATH),
                    "--out-dir", str(OUTPUT_DIR / "profile"),
                ]
                subprocess.run(cmd_prof, check=True)
                print("✅ Profiling terminé →", OUTPUT_DIR / "profile")
                """),
        ]

    if tool_key in ("kraken", "kraken2", "bracken"):
        return [
            _code_cell("""\
                import subprocess

                report_out = OUTPUT_DIR / "kraken2_report.txt"
                cmd = [
                    "kraken2",
                    "--db",      str(DB_PATH),
                    "--threads", str(N_THREADS),
                    "--output",  str(OUTPUT_DIR / "kraken2.out"),
                    "--report",  str(report_out),
                    str(INPUT_FASTQ),
                ]
                print("Kraken2:", " ".join(cmd))
                subprocess.run(cmd, check=True)
                print("✅ Kraken2 terminé →", report_out)
                """),
            _code_cell("""\
                # Bracken — ré-estimation d'abondance
                bracken_out = OUTPUT_DIR / "bracken_species.txt"
                cmd_b = [
                    "bracken",
                    "-d", str(DB_PATH),
                    "-i", str(report_out),
                    "-o", str(bracken_out),
                    "-l", "S",   # niveau espèce
                    "-t", "10",  # seuil minimal de reads
                ]
                subprocess.run(cmd_b, check=True)
                print("✅ Bracken terminé →", bracken_out)
                """),
        ]

    if tool_key == "metaphlan":
        return [_code_cell("""\
            import subprocess

            profile_out  = OUTPUT_DIR / "metaphlan_profile.txt"
            bowtie2_out  = OUTPUT_DIR / "metaphlan.bowtie2.bz2"

            cmd = [
                "metaphlan", str(INPUT_FASTQ),
                "--input_type", "fastq",
                "--bowtie2db",  str(DB_PATH),
                "--nproc",      str(N_THREADS),
                "-o",           str(profile_out),
                "--bowtie2out", str(bowtie2_out),
            ]
            print("MetaPhlAn:", " ".join(cmd))
            subprocess.run(cmd, check=True)
            print("✅ MetaPhlAn terminé →", profile_out)
            """)]

    if tool_key == "metabuli":
        return [_code_cell("""\
            import subprocess

            cmd = [
                "metabuli", "classify",
                str(INPUT_FASTQ),
                str(DB_PATH),
                str(OUTPUT_DIR),
                "--threads", str(N_THREADS),
            ]
            print("Metabuli:", " ".join(cmd))
            subprocess.run(cmd, check=True)
            print("✅ Metabuli terminé →", OUTPUT_DIR)
            """)]

    # Générique
    return [_code_cell(f"""\
        # ⚠️ Remplacez par la commande réelle de {tool_name}
        import subprocess

        cmd = ["{tool_key}", "--help"]
        subprocess.run(cmd)
        print("→ Ajoutez la commande d'exécution pour {tool_name}")
        """)]


def _taxo_badge(ts) -> str:
    if ts is None:
        return "—"
    if isinstance(ts, list):
        return " + ".join(str(x).upper() for x in ts)
    return str(ts).upper()
